[workspace]
members = [
    "glyphr",
    "glyphr-macros",
]
resolver = "2"

[workspace.package]
authors = ["Alessandro Bridi <ale.bridi15@gmail.com>"]
license = "Apache-2.0"
edition = "2024"
repository = "https://github.com/Bridiro/glyphr"
